{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CURSED_PEARL",
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 432,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 333,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 80,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.CURSED_PEARL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.IRON_WAVE"
              }
            ],
            "current_gold": 445,
            "current_hp": 80,
            "damage_taken": 3,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 3,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.STRIKE_DUMMY"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THRASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFERNAL_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GOLD_AXE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLOODLETTING"
              },
              {
                "id": "CARD.RUPTURE"
              },
              {
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 74,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 371,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              },
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": false
              },
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 88,
            "current_hp": 80,
            "damage_taken": 1,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PILLAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROLONG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ONE_TWO_PUNCH"
              }
            ],
            "current_gold": 15,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 73,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOOD_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": false
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": false
              },
              {
                "choice": "RELIC.BURNING_STICKS",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 15,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.RUPTURE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 34,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BEETLE_JUICE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFLAME"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HEMOKINESIS"
              }
            ],
            "current_gold": 51,
            "current_hp": 76,
            "damage_taken": 10,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 51,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BLOODLETTING"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 102,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MUMMIFIED_HAND",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.JUGGLING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.JUGGLING"
              }
            ],
            "current_gold": 122,
            "current_hp": 71,
            "damage_taken": 11,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PUNCH_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 122,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.JUGGLING"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAPPLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BODY_SLAM"
              }
            ],
            "current_gold": 159,
            "current_hp": 52,
            "damage_taken": 25,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOOD_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BEETLE_JUICE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 202,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 43,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.ULTIMATE_DEFEND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THE_BOMB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IMPATIENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ULTIMATE_DEFEND"
              }
            ],
            "current_gold": 202,
            "current_hp": 47,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.RIP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 202,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ONE_TWO_PUNCH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.DEMON_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CONFLAGRATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEMON_FORM"
              }
            ],
            "current_gold": 302,
            "current_hp": 39,
            "damage_taken": 30,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.BLOOD_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 302,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 41,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEMON_FORM",
              "CARD.BODY_SLAM",
              "CARD.ULTIMATE_DEFEND",
              "CARD.IRON_WAVE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TWIN_STRIKE"
              }
            ],
            "current_gold": 315,
            "current_hp": 70,
            "damage_taken": 16,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.METAMORPHOSIS"
              }
            ],
            "current_gold": 315,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.LET_IT_IN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SPIRIT_GRAFTER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.PILLAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 15,
                "id": "CARD.ULTIMATE_DEFEND"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.PILLAGE"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 15,
                "id": "CARD.ULTIMATE_DEFEND"
              }
            ],
            "current_gold": 326,
            "current_hp": 78,
            "damage_taken": 8,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THRASH"
                },
                "was_picked": false
              }
            ],
            "current_gold": 346,
            "current_hp": 57,
            "damage_taken": 27,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.VICIOUS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VICIOUS"
              }
            ],
            "current_gold": 391,
            "current_hp": 49,
            "damage_taken": 14,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.DARK_SHACKLES"
            ],
            "bought_relics": [
              "RELIC.AKABEKO"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SPITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FIGHT_ME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_GEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DARK_SHACKLES"
              },
              {
                "id": "CARD.EVIL_EYE"
              }
            ],
            "current_gold": 0,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 391,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.AKABEKO",
                "was_picked": true
              },
              {
                "choice": "RELIC.UNCEASING_TOP",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 52,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 52,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 96,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 44,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 141,
            "current_hp": 7,
            "damage_taken": 48,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE",
              "POTION.DEXTERITY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 10
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 141,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TAUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 154,
            "current_hp": 28,
            "damage_taken": 9,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LOUSE_PROGENITOR_NORMAL",
            "monster_ids": [
              "MONSTER.LOUSE_PROGENITOR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 30,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SETUP_STRIKE"
              }
            ],
            "current_gold": 199,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ENERGY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 31,
                  "id": "CARD.VICIOUS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CONFLAGRATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.VICIOUS"
              }
            ],
            "current_gold": 217,
            "current_hp": 18,
            "damage_taken": 22,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.BLOCK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
            "monster_ids": [
              "MONSTER.HUNTER_KILLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 217,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 39,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.FEED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BRAND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THRASH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FEED"
              }
            ],
            "current_gold": 317,
            "current_hp": 7,
            "damage_taken": 56,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.COLORLESS_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "TANXS_WHISTLE",
                "title": {
                  "key": "TANXS_WHISTLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.BASH"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.IRON_WAVE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 21,
                  "id": "CARD.PILLAGE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 317,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 73,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STAMPEDE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 329,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 329,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                },
                "variables": {
                  "FoulPotions": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.POTION_COURIER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.PYRE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PYRE"
              }
            ],
            "current_gold": 349,
            "current_hp": 75,
            "damage_taken": 14,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 83,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 249,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.GOLD.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Potion of Binding"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Akabeko"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.GAMBLING_CHIP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 249,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PYRE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 40,
                  "id": "CARD.INFERNAL_BLADE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.INFERNAL_BLADE"
              }
            ],
            "current_gold": 260,
            "current_hp": 66,
            "damage_taken": 33,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 86,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CONSTRUCT_MENAGERIE_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 305,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HOWL_FROM_BEYOND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_GAMBIT"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 23,
                "id": "CARD.VICIOUS"
              }
            ],
            "current_gold": 230,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RUINED_HELMET",
                "was_picked": false
              },
              {
                "choice": "RELIC.CLOAK_CLASP",
                "was_picked": false
              },
              {
                "choice": "RELIC.GHOST_SEED",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 269,
            "current_hp": 47,
            "damage_taken": 25,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 269,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.EVIL_EYE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 45,
                  "id": "CARD.FLAME_BARRIER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FLAME_BARRIER"
              }
            ],
            "current_gold": 279,
            "current_hp": 39,
            "damage_taken": 14,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.POTION_OF_BINDING"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "current_gold": 279,
            "current_hp": 0,
            "damage_taken": 39,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.IRON_WAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.BLOODLETTING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.RUPTURE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.MOLTEN_FIST"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.ONE_TWO_PUNCH"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.HEMOKINESIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.JUGGLING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.BODY_SLAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.DEMON_FORM"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.TWIN_STRIKE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.METAMORPHOSIS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.ULTIMATE_DEFEND"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 21,
          "id": "CARD.PILLAGE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "CARD.DARK_SHACKLES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 24,
          "id": "CARD.EVIL_EYE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 30,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.VICIOUS"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.FEED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 37,
          "id": "CARD.PYRE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.INFERNAL_BLADE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 45,
          "id": "CARD.FLAME_BARRIER"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.POTION_OF_BINDING",
          "slot_index": 0
        },
        {
          "id": "POTION.FORTIFIER",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CURSED_PEARL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.MUMMIFIED_HAND"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.KUSARIGAMA"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.BELLOWS"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.AKABEKO"
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 6
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 30,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.GAMBLING_CHIP"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.LANTERN"
        }
      ]
    }
  ],
  "run_time": 4739,
  "schema_version": 8,
  "seed": "YXL1W06Q1X",
  "start_time": 1774626900,
  "was_abandoned": false,
  "win": false
}