{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.TEST_SUBJECT_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "POMANDER",
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POMANDER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.POMANDER",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.ZAP"
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "MASSIVE_SCROLL",
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAFY_POULTICE",
                "title": {
                  "key": "LEAFY_POULTICE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SQUEEZE"
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PRECISE_SCISSORS",
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PANIC_BUTTON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OMNISLICE"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 112,
            "current_hp": 45,
            "damage_taken": 15,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.DEFILE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEFILE"
              }
            ],
            "current_gold": 108,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.DEFLECT"
              }
            ],
            "current_gold": 107,
            "current_hp": 53,
            "damage_taken": 3,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 151,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 82,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 144,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 142,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 483,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 332,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 481,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 66,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 337,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 337,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 502,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 360,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BARRAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BOOST_AWAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.BARRAGE"
              }
            ],
            "current_gold": 494,
            "current_hp": 37,
            "damage_taken": 15,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COUNTDOWN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RATTLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BORROWED_TIME"
              }
            ],
            "current_gold": 496,
            "current_hp": 45,
            "damage_taken": 7,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 515,
            "current_hp": 39,
            "damage_taken": 14,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARKNESS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.BEAM_CELL"
              }
            ],
            "current_gold": 508,
            "current_hp": 32,
            "damage_taken": 5,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 511,
            "current_hp": 44,
            "damage_taken": 1,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 530,
            "current_hp": 37,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.THUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.THUNDER"
              }
            ],
            "current_gold": 523,
            "current_hp": 25,
            "damage_taken": 7,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 60,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VEILPIERCER"
              }
            ],
            "current_gold": 521,
            "current_hp": 42,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.POISONED_STAB"
              }
            ],
            "current_gold": 539,
            "current_hp": 28,
            "damage_taken": 9,
            "gold_gained": 69,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 60,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 523,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEAM_CELL"
            ]
          },
          {
            "current_gold": 521,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SQUEEZE"
            ]
          },
          {
            "current_gold": 539,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 562,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.TOXIC_EGG",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 552,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 577,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 562,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 552,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BORROWED_TIME"
            ]
          },
          {
            "current_gold": 577,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NOXIOUS_FUMES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 11,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 11,
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 569,
            "current_hp": 33,
            "damage_taken": 16,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.LETHALITY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_FROM_BELOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LETHALITY"
              }
            ],
            "current_gold": 566,
            "current_hp": 32,
            "damage_taken": 10,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.DAGGER_THROW"
              }
            ],
            "current_gold": 586,
            "current_hp": 31,
            "damage_taken": 18,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CULTISTS_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.DAMP_CULTIST"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.FINESSE"
              },
              {
                "id": "CARD.FEEDING_FRENZY"
              }
            ],
            "current_gold": 359,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CAVIAR.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SPICY_SNAPPY.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CAVIAR.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.FRIED_EEL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SEAPUNK_SALAD.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.GRAB_SOMETHING_OFF_THE_BELT.options.LEAVE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 210,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 90,
            "max_hp_gained": 8,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "upgraded_cards": [
              "CARD.DEFEND_DEFECT"
            ]
          },
          {
            "current_gold": 426,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Seapunk Salad"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CAVIAR.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Seapunk Salad"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SPICY_SNAPPY.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Seapunk Salad"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Seapunk Salad"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.GRAB_SOMETHING_OFF_THE_BELT.options.LEAVE.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Seapunk Salad"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 140,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 70,
            "max_hp_gained": 4,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "upgraded_cards": [
              "CARD.LETHALITY"
            ]
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CATASTROPHE"
              }
            ],
            "current_gold": 446,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.FRIED_EEL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SPICY_SNAPPY.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.GRAB_SOMETHING_OFF_THE_BELT.options.LEAVE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 140,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "upgraded_cards": [
              "CARD.OMNISLICE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ENDLESS_CONVEYOR",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.HAILSTORM"
              }
            ],
            "current_gold": 26,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 333,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ]
          },
          {
            "bought_relics": [
              "RELIC.PUNCH_DAGGER"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINESSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 5,
                    "id": "ENCHANTMENT.MOMENTUM"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.UNLEASH"
                },
                "enchantment": "ENCHANTMENT.MOMENTUM"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 109,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 317,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.BONE_BREW",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PUNCH_DAGGER",
                "was_picked": true
              },
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.INFINITE_BLADES"
              },
              {
                "floor_added_to_deck": 13,
                "id": "CARD.CLOAK_AND_DAGGER"
              },
              {
                "floor_added_to_deck": 13,
                "id": "CARD.LEADING_STRIKE"
              }
            ],
            "current_gold": 13,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 433,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 57,
            "current_hp": 26,
            "damage_taken": 25,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.JOSS_PAPER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.MISERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MISERY"
              }
            ],
            "current_gold": 140,
            "current_hp": 20,
            "damage_taken": 36,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 45,
            "current_hp": 16,
            "damage_taken": 35,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 57,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 140,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 45,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 16,
                  "id": "CARD.RAINBOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ECHO_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 16,
                "id": "CARD.RAINBOW"
              }
            ],
            "current_gold": 132,
            "current_hp": 12,
            "damage_taken": 41,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.GLIMPSE_BEYOND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.OBLIVION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.END_OF_DAYS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLIMPSE_BEYOND"
              }
            ],
            "current_gold": 215,
            "current_hp": 6,
            "damage_taken": 35,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.ABRASIVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MURDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHADOW_STEP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.ABRASIVE"
              }
            ],
            "current_gold": 120,
            "current_hp": 26,
            "damage_taken": 11,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 132,
            "current_hp": 74,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 62,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.BARRAGE",
              "CARD.HAILSTORM",
              "CARD.THUNDER",
              "CARD.COOLHEADED"
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.TEZCATARAS_EMBER"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                },
                "enchantment": "ENCHANTMENT.TEZCATARAS_EMBER"
              }
            ],
            "current_gold": 215,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 51,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_SOUP",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 120,
            "current_hp": 61,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 35,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.SEAL_OF_GOLD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.FINESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DARKNESS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.FINESSE"
              },
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.BOOT_SEQUENCE"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 12,
                "id": "CARD.FINESSE"
              }
            ],
            "current_gold": 145,
            "current_hp": 54,
            "damage_taken": 20,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.VEILPIERCER"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.SEVERANCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.VEILPIERCER"
              }
            ],
            "current_gold": 230,
            "current_hp": 56,
            "damage_taken": 16,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.FLICK_FLACK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.CATASTROPHE"
              }
            ],
            "current_gold": 108,
            "current_hp": 54,
            "damage_taken": 7,
            "gold_gained": 8,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 190,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "current_gold": 296,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Lost Wisp"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 66,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "current_gold": 183,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.LOST_WISP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.SUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CHILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.SUNDER"
              }
            ],
            "current_gold": 203,
            "current_hp": 53,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.WISP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WISP"
              }
            ],
            "current_gold": 306,
            "current_hp": 47,
            "damage_taken": 9,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.PHANTOM_BLADES"
              }
            ],
            "current_gold": 175,
            "current_hp": 49,
            "damage_taken": 5,
            "gold_gained": 12,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.COMPACT"
              }
            ],
            "current_gold": 203,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CLEANSE"
              }
            ],
            "current_gold": 306,
            "current_hp": 47,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "cards_gained": [
              {
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 175,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.SHARE_KNOWLEDGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 203,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 306,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 175,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.INFINITE_BLADES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.HOTFIX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 23,
                "id": "CARD.HOTFIX"
              }
            ],
            "current_gold": 233,
            "current_hp": 52,
            "damage_taken": 28,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_used": [
              "POTION.WEAK_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.INVOKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BONE_SHARDS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.INVOKE"
              }
            ],
            "current_gold": 336,
            "current_hp": 26,
            "damage_taken": 42,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.DEXTERITY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 23,
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 174,
            "current_hp": 22,
            "damage_taken": 27,
            "gold_gained": 29,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 268,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.RAINBOW_RING",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 369,
            "current_hp": 26,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 206,
            "current_hp": 22,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.UNSETTLING_LAMP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 268,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 369,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 206,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 282,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FETCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 382,
            "current_hp": 26,
            "damage_taken": 21,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 26,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 26,
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 190,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 25,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.POTION_OF_BINDING"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SPINY_TOAD_NORMAL",
            "monster_ids": [
              "MONSTER.SPINY_TOAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 282,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BALL_LIGHTNING"
            ]
          },
          {
            "current_gold": 382,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 190,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ABRASIVE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 28,
                "id": "CARD.PRODUCTION"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 71,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 136,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          },
          {
            "bought_relics": [
              "RELIC.INTIMIDATING_HELMET"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROWESS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MELANCHOLY"
              }
            ],
            "current_gold": 43,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 339,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              },
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.SPEEDSTER"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 37,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 78,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 71,
            "current_hp": 70,
            "damage_taken": 9,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.REJECTION.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_NECROBINDER"
              }
            ],
            "current_gold": 43,
            "current_hp": 53,
            "damage_taken": 9,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.REJECTION.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 37,
            "current_hp": 34,
            "damage_taken": 9,
            "event_choices": [
              {
                "title": {
                  "key": "SPIRIT_GRAFTER.pages.INITIAL.options.REJECTION.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SPIRIT_GRAFTER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 71,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DUALCAST"
            ]
          },
          {
            "current_gold": 43,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 17,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 37,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 31,
                  "id": "CARD.REBOOT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HYPERBEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAINBOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 31,
                "id": "CARD.REBOOT"
              }
            ],
            "current_gold": 146,
            "current_hp": 1,
            "damage_taken": 70,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.OBLIVION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_SCYTHE",
                  "props": {
                    "ints": [
                      {
                        "name": "CurrentDamage",
                        "value": 13
                      },
                      {
                        "name": "IncreasedDamage",
                        "value": 0
                      }
                    ]
                  }
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MISERY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 118,
            "current_hp": 12,
            "damage_taken": 58,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_used": [
              "POTION.WEAK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHADOWMELD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCELERANT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 77,
            "current_hp": 11,
            "damage_taken": 44,
            "gold_gained": 75,
            "gold_lost": 35,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_used": [
              "POTION.POWDERED_DEMISE",
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
            "monster_ids": [
              "MONSTER.KNOWLEDGE_DEMON"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 5,
                  "id": "CARD.BARRAGE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 14,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 20,
                  "id": "CARD.SUNDER"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 146,
            "current_hp": 72,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 71,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.SQUEEZE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.SEVERANCE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.VEILPIERCER"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 118,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 46,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 77,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 47,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_HAMMER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 33,
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GLACIER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 33,
                "id": "CARD.SHADOW_SHIELD"
              }
            ],
            "current_gold": 158,
            "current_hp": 65,
            "damage_taken": 7,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 4,
            "player_id": 76561198069144415,
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DANSE_MACABRE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PARSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 76561198089456579
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 72,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 15,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.CORRUPTED"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_DEFECT"
                },
                "enchantment": "ENCHANTMENT.CORRUPTED"
              }
            ],
            "current_gold": 158,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.APPROACH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.SHARED_FATE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_NECROBINDER"
                }
              }
            ],
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Corrupted"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.OUTBREAK"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              }
            ],
            "current_gold": 72,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SYMBIOTE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              }
            ],
            "current_gold": 158,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.ENERGIZED.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 5
                    }
                  ]
                }
              }
            ],
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.WISDOM.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              }
            ],
            "current_gold": 72,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.ENERGIZED.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TINKER_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 158,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.GRAB_POTIONS.title",
                  "table": "events"
                },
                "variables": {
                  "FoulPotions": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 72,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.RANSACK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.POTION_COURIER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 158,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SUNDER"
            ]
          },
          {
            "current_gold": 128,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.INVOKE"
            ]
          },
          {
            "current_gold": 72,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.AFTERIMAGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 189,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "relic_choices": [
              {
                "choice": "RELIC.CAPTAINS_WHEEL",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 164,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 106,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 39,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 39,
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 222,
            "current_hp": 51,
            "damage_taken": 14,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.LIQUID_BRONZE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GAME_PIECE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 195,
            "current_hp": 27,
            "damage_taken": 31,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 39,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 39,
                "id": "CARD.TACTICIAN"
              }
            ],
            "current_gold": 100,
            "current_hp": 27,
            "damage_taken": 46,
            "gold_gained": 29,
            "gold_lost": 35,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_used": [
              "POTION.REGEN_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEFLECT",
              "CARD.NEUTRALIZE",
              "CARD.DEFEND_SILENT",
              "CARD.DEFEND_SILENT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 229,
            "current_hp": 49,
            "damage_taken": 2,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 40,
                  "id": "CARD.DREDGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.DREDGE"
              }
            ],
            "current_gold": 207,
            "current_hp": 10,
            "damage_taken": 19,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 40,
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 89,
            "current_hp": 27,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 20,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 229,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 207,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 89,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 256,
            "current_hp": 70,
            "damage_taken": 4,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LIZARD_TAIL",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 233,
            "current_hp": 21,
            "damage_taken": 11,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOOKMARK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 42,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 42,
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 85,
            "current_hp": 47,
            "damage_taken": 1,
            "gold_gained": 31,
            "gold_lost": 35,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TINY_MAILBOX",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEFEND_SILENT",
              "CARD.STRIKE_SILENT",
              "CARD.CLOAK_AND_DAGGER",
              "CARD.CALCULATED_GAMBLE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.MODDED"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 43,
                "id": "CARD.MODDED"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_DEFECT"
              }
            ],
            "current_gold": 0,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 156,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "bought_colorless": [
              "CARD.FASTEN"
            ],
            "bought_potions": [
              "POTION.MAZALETHS_GIFT",
              "POTION.ENERGY_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEACON_OF_HOPE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FASTEN"
              }
            ],
            "current_gold": 193,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 200,
            "gold_lost": 0,
            "gold_spent": 240,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_choices": [
              {
                "choice": "POTION.MAZALETHS_GIFT",
                "was_picked": true
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ],
            "potion_used": [
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PRAYER_WHEEL",
                "was_picked": false
              },
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.THE_ABACUS",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 34,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 51,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 0,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "rest_site_choices": [
              "MEND"
            ]
          },
          {
            "current_gold": 193,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.MELANCHOLY"
            ]
          },
          {
            "current_gold": 34,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 0,
            "current_hp": 28,
            "damage_taken": 42,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415,
            "potion_used": [
              "POTION.VULNERABLE_POTION",
              "POTION.GAMBLERS_BREW"
            ]
          },
          {
            "current_gold": 193,
            "current_hp": 1,
            "damage_taken": 56,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 3,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579
          },
          {
            "current_gold": 4,
            "current_hp": 30,
            "damage_taken": 38,
            "gold_gained": 0,
            "gold_lost": 30,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369,
            "potion_used": [
              "POTION.ENERGY_POTION",
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 22
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 0,
            "current_hp": 0,
            "damage_taken": 71,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 43,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198069144415
          },
          {
            "current_gold": 193,
            "current_hp": 0,
            "damage_taken": 3,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198089456579,
            "potion_used": [
              "POTION.MAZALETHS_GIFT",
              "POTION.ENERGY_POTION"
            ]
          },
          {
            "current_gold": 4,
            "current_hp": 0,
            "damage_taken": 30,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199377009369
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.CORRUPTED"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 5,
          "id": "CARD.BARRAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.BEAM_CELL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 7,
          "id": "CARD.THUNDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.COOLHEADED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.FEEDING_FRENZY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.HAILSTORM"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 14,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.RAINBOW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.FINESSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.BOOT_SEQUENCE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 20,
          "id": "CARD.SUNDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.COMPACT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.HOTFIX"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.PRODUCTION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.REBOOT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.SHADOW_SHIELD"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.HOLOGRAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.MODDED"
        }
      ],
      "id": 76561198069144415,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.POMANDER"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.TOXIC_EGG"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.JOSS_PAPER",
          "props": {
            "ints": [
              {
                "name": "CardsExhausted",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.GREMLIN_HORN"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.RAINBOW_RING"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.CAPTAINS_WHEEL"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.GAME_PIECE"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.LIZARD_TAIL",
          "props": {
            "bools": [
              {
                "name": "WasUsed",
                "value": true
              }
            ]
          }
        }
      ]
    },
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.TEZCATARAS_EMBER"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "enchantment": {
            "amount": 5,
            "id": "ENCHANTMENT.MOMENTUM"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.SQUEEZE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.DEFILE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.BORROWED_TIME"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.LETHALITY"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.MISERY"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.GLIMPSE_BEYOND"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.VEILPIERCER"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.SEVERANCE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.WISP"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.CLEANSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.INVOKE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.MELANCHOLY"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.SCULPTING_STRIKE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.SHARED_FATE"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 5
              }
            ]
          }
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.DREDGE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.FASTEN"
        }
      ],
      "id": 76561198089456579,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BOOK_OF_FIVE_RINGS",
          "props": {
            "ints": [
              {
                "name": "CardsAdded",
                "value": 15
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.PUNCH_DAGGER"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.NUTRITIOUS_SOUP"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.NUNCHAKU",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 113
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.BOOKMARK"
        }
      ]
    },
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.OMNISLICE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.GREED"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.ACROBATICS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.ABRASIVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.PHANTOM_BLADES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.CALCULATED_GAMBLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.BACKFLIP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 26,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.SPEEDSTER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.OUTBREAK"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.TACTICIAN"
        },
        {
          "floor_added_to_deck": 40,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.ACROBATICS"
        }
      ],
      "id": 76561199377009369,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.STURDY_CLAMP"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.SEAL_OF_GOLD"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.VAMBRACE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.UNSETTLING_LAMP"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.WAR_HAMMER"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.TINY_MAILBOX"
        }
      ]
    }
  ],
  "run_time": 5414,
  "schema_version": 8,
  "seed": "27VDHNSA7D",
  "start_time": 1776291612,
  "was_abandoned": false,
  "win": false
}